cd(deploy): deploy.yml 수정
- Docker -> Java 로 환경 변환

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,72 +1,125 @@
-name: Backend-deploy
+name: Deploy-service
+
+permissions:
+  contents: read
+  pull-requests: write
 
 on:
   push:
-    branches: [ "main" ]
-
-  workflow_dispatch:
-
-env:
-  # DockerHub
-  DOCKER_USERNAME: giyeonlee
-  # AWS & Elastic Bean Stalk
-  AWS_REGION: ap-northeast-2
-  EB_ENVIRONMENT_NAME: Triumers-Final-Back-env
-  EB_APPLICATION_NAME: Triumers-Back
-  EB_DEPLOYMENT_PACKAGE: elasticbeanstalk/docker-compose.yml
+    branches: ["main", "dev"]
 
 jobs:
-  deploy:
+  build:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
-      - name: Set up JDK
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Set up JDK 17
         uses: actions/setup-java@v4
         with:
           java-version: '17'
           distribution: 'corretto'
 
-      - name: Make gradle.properties
+      - name: Grant execute permission for gradlew
+        run: chmod +x ./gradlew
+        shell: bash
+
+      - name: Install envsubst
+        run: sudo apt-get install -y gettext
+
+      - name: Create application.yml.template
         run: |
-          echo "${{ secrets.GRADLE_PROPERTIES }}" | base64 --decode > gradle.properties
+          mkdir -p src/main/resources
+          cat > src/main/resources/application.yml.template <<EOL
+          server:
+            port: 5000
+          
+          spring:
+            datasource:
+              driver-class-name: org.mariadb.jdbc.Driver
+              url: jdbc:mariadb://\${RDS_HOSTNAME}:\${RDS_PORT}/\${RDS_DB_NAME}
+              username: \${RDS_USERNAME}
+              password: \${RDS_PASSWORD}
+          
+            jpa:
+              generate-ddl: false
+              show-sql: true
+              database: mysql
+              properties:
+                hibernate:
+                  '[format_sql]': true
+          EOL
 
-      - name: Build Number
-        id: build-number
-        run: echo "::set-output name=BUILD_NUMBER::$(date '+%-d.%-m.%Y.%-H.%-M.%-S')"
+      - name: Set Yaml
+        run: |
+          envsubst < src/main/resources/application.yml.template > src/main/resources/application.yml
+          echo "Generated application.yml:"
+          cat src/main/resources/application.yml
+        env:
+          RDS_HOSTNAME: ${{ secrets.DB_HOST }}
+          RDS_PORT: ${{ secrets.DB_PORT }}
+          RDS_DB_NAME: ${{ secrets.DB_NAME }}
+          RDS_USERNAME: ${{ secrets.DB_USERNAME }}
+          RDS_PASSWORD: ${{ secrets.DB_PASSWORD }}
 
-      - name: Docker Login
-        uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
+      - name: Check for Tests
+        run: |
+          if git diff --name-only origin/main HEAD | grep -qvE '(\.xml$|\.yml$|config/)'; then
+            if [ -z "$(find src/test -name '*ServiceTest.java')" ]; then
+              echo "No ServiceTest found, failing the build."
+              exit 1
+            fi
+          else
+            echo "Only configuration files changed, skipping test check."
+          fi
+
+      - name: Build with Gradle
+        run: ./gradlew clean build
+
+      - name: Get current time
+        uses: 1466587594/get-current-time@v2
+        id: current-time
         with:
-          username: ${{ env.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
+          format: YYYY-MM-DDTHH-mm-ss
+          utcOffset: "+09:00"
 
-      - name: Stop and remove container
+      - name: Show Current Time
+        run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}"
+        shell: bash
+
+      - name: ChatGPT codeReviewer
+        uses: anc95/ChatGPT-CodeReview@v1.0.13
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
+
+          # Optional
+          LANGUAGE: Korean
+          OPENAI_API_ENDPOINT: https://api.openai.com/v1
+          MODEL: gpt-3.5-turbo
+          PROMPT: Please check if there are any confusions or irregularities in the following code diff
+          top_p: 1
+          temperature: 1
+          max_tokens: 10000
+          MAX_PATCH_LENGTH: 10000
+
+      - name: Generate deployment package
         run: |
-          CONTAINER_ID=$(docker ps -q --filter ancestor=giyeonlee/triumers-back:latest)
-          if [ ! -z "$CONTAINER_ID" ]; then
-            docker stop $CONTAINER_ID
-            docker rm $CONTAINER_ID
-          fi
-
-      - name: Remove Docker image
-        run: |
-          IMAGE_ID=$(docker images -q giyeonlee/triumers-back:latest)
-          if [ ! -z "$IMAGE_ID" ]; then
-            docker rmi $IMAGE_ID
-          fi
-
-      - name: Push to Dockerhub
-        run: ./gradlew jib
+          mkdir -p deploy
+          cp build/libs/*.jar deploy/application.jar
+          cp Procfile deploy/Procfile
+          cp -r .ebextensions deploy/.ebextensions
+          cp -r .platform deploy/.platform
+          cd deploy && zip -r deploy.zip .  
 
       - name: Beanstalk Deploy
-        uses: einaregilsson/beanstalk-deploy@ebe3476a4ce991d54336935e75e78dd9d86f9408
+        uses: einaregilsson/beanstalk-deploy@v22
         with:
           aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          region: ${{ env.AWS_REGION }}
-          environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
-          application_name: ${{ env.EB_APPLICATION_NAME }}
-          deployment_package: ${{ env.EB_DEPLOYMENT_PACKAGE }}
-          version_label: ${{ steps.build-number.outputs.BUILD_NUMBER }}
-          version_description: Version ${{steps.build-number.outputs.BUILD_NUMBER}} deployed via github actions ${{ github.sha }}
-          wait_for_deployment: 60
+          application_name: Triumers-Back
+          environment_name: Triumers-Back-env
+          version_label: github-action-${{steps.current-time.outputs.formattedTime}}
+          region: ap-northeast-2
+          deployment_package: deploy/deploy.zip
